
import os

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
HUGGING_FACE_API = os.getenv("HUGGING_FACE_HUB_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID")
AT_USERNAME = os.getenv("AT_USERNAME")
AT_API_KEY = os.getenv("AT_API_KEY")